"""empty message

Revision ID: 04327d0bebb5
Revises: af24f1c0c36d
Create Date: 2026-04-05 00:09:19.826659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04327d0bebb5'
down_revision = 'af24f1c0c36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
