"""empty message

Revision ID: 107fc6e34eed
Revises: 52b35a0ff71d
Create Date: 2026-04-06 23:15:05.739752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107fc6e34eed'
down_revision = '52b35a0ff71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address_start', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lat_finish', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng_finish', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address_finish', sa.String(length=255), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_gerente', sa.String(length=120), nullable=True))
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('nombre_gerente')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('address_finish')
        batch_op.drop_column('lng_finish')
        batch_op.drop_column('lat_finish')
        batch_op.drop_column('address_start')
        batch_op.drop_column('lng_start')
        batch_op.drop_column('lat_start')

    # ### end Alembic commands ###
