"""empty message

Revision ID: 1a6b0275ecae
Revises: 08175eb6e818
Create Date: 2026-04-03 00:03:37.039589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6b0275ecae'
down_revision = '08175eb6e818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_estimado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('precio_recomendado', sa.Float(), nullable=True))

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('precio_recomendado')
        batch_op.drop_column('tiempo_estimado')

    # ### end Alembic commands ###
