"""empty message

Revision ID: 33984929278c
Revises: a69081f44766
Create Date: 2026-04-06 20:10:06.859908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33984929278c'
down_revision = 'a69081f44766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
