"""empty message

Revision ID: 39eaeee17454
Revises: d2af2bf03bce
Create Date: 2026-04-06 15:40:32.883479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eaeee17454'
down_revision = 'd2af2bf03bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_gerente', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=250), nullable=True))
        batch_op.drop_column('capacidad')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('direccion')
        batch_op.drop_column('nombre_gerente')

    # ### end Alembic commands ###
