"""empty message

Revision ID: 39f29583e5be
Revises: 2eca4c735c91
Create Date: 2026-03-24 23:19:20.959794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f29583e5be'
down_revision = '2eca4c735c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establecimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('total_sucursales', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('establecimiento')
    # ### end Alembic commands ###
