"""empty message

Revision ID: 408fadb41dda
Revises: b549e54609c2
Create Date: 2026-03-29 15:54:13.841870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408fadb41dda'
down_revision = 'b549e54609c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('clave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
