"""empty message

Revision ID: 52b35a0ff71d
Revises: f41d8ac53cbd
Create Date: 2026-04-06 22:56:36.076518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b35a0ff71d'
down_revision = 'f41d8ac53cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('nombre_gerente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_gerente', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
