"""empty message

Revision ID: 696623d1709b
Revises: 39f29583e5be
Create Date: 2026-03-25 19:23:38.702753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696623d1709b'
down_revision = '39f29583e5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('establecimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('total_sucursales', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=129),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=129),
               existing_nullable=False)

    op.drop_table('establecimiento')
    op.drop_table('tipo')
    op.drop_table('client')
    # ### end Alembic commands ###
