"""empty message

Revision ID: 84ba6c8844c0
Revises: c157dd7ddaf3
Create Date: 2026-04-03 21:26:48.871028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ba6c8844c0'
down_revision = 'c157dd7ddaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
