"""empty message

Revision ID: 91dbe7eb7744
Revises: d377d4a44900
Create Date: 2026-04-06 23:33:26.504006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dbe7eb7744'
down_revision = 'd377d4a44900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address_start', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lat_finish', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng_finish', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address_finish', sa.String(length=255), nullable=True))
        batch_op.drop_column('lat')
        batch_op.drop_column('address')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('address_finish')
        batch_op.drop_column('lng_finish')
        batch_op.drop_column('lat_finish')
        batch_op.drop_column('address_start')
        batch_op.drop_column('lng_start')
        batch_op.drop_column('lat_start')

    # ### end Alembic commands ###
