"""empty message

Revision ID: 9cde797c4c44
Revises: d5642df8660e
Create Date: 2026-03-27 16:41:59.071728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cde797c4c44'
down_revision = 'd5642df8660e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liner_nombre', sa.String(length=100), nullable=False),
    sa.Column('liner_email', sa.String(length=120), nullable=False),
    sa.Column('liner_password', sa.String(), nullable=False),
    sa.Column('liner_foto', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liner_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liner')
    # ### end Alembic commands ###
