"""empty message

Revision ID: 9e00fdbbd954
Revises: 696623d1709b
Create Date: 2026-03-25 19:28:00.036245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e00fdbbd954'
down_revision = '696623d1709b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fila_activa', sa.Boolean(), nullable=False),
    sa.Column('tiempo_por_cliente', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sucursal')
    # ### end Alembic commands ###
