"""empty message

Revision ID: af24f1c0c36d
Revises: 84ba6c8844c0
Create Date: 2026-04-04 23:35:58.099927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af24f1c0c36d'
down_revision = '84ba6c8844c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
