"""empty message

Revision ID: d2af2bf03bce
Revises: 84ba6c8844c0
Create Date: 2026-04-05 19:08:20.983467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2af2bf03bce'
down_revision = '84ba6c8844c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_estimado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('precio_recomendado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=500), nullable=True))
        batch_op.alter_column('capacidad',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.alter_column('capacidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('imagen')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('precio_recomendado')
        batch_op.drop_column('tiempo_estimado')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###
