"""empty message

Revision ID: de7bc8961451
Revises: bb7b2f032938
Create Date: 2026-03-24 17:08:10.633901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7bc8961451'
down_revision = 'bb7b2f032938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_posicion_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('ticket_posicion_key'), ['posicion'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
