"""empty message

Revision ID: f41d8ac53cbd
Revises: 9ee7bfe076ee
Create Date: 2026-04-06 22:47:40.537469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41d8ac53cbd'
down_revision = '9ee7bfe076ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('imagen')
        batch_op.drop_column('address')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###
